### ISSUE TITLE
v6.4.0 crashing homebridge

### ISSUE THREAD

**Issue by Infallibleman** [NorthernMan54/homebridge-tcc#104]
the latest version of 6.4.0 is causing consistent crashes of the homebridge platform, getting stuck in rolling reboot and crash.

Below is the error seen when it crashes.

`[5/8/2021, 8:10:37 AM] [TPLink-Kasa] homebridge-tplink-smarthome v6.4.0, node v12.22.1, homebridge v1.3.4, api v2.7
[5/8/2021, 8:10:38 AM] ConfigParseError: Error parsing config:
`devices/0` must be object
    at Object.parseConfig (/usr/lib/node_modules/homebridge-tplink-smarthome/src/config.ts:259:11)
    at new TplinkSmarthomePlatform (/usr/lib/node_modules/homebridge-tplink-smarthome/src/platform.ts:70:19)
    at /usr/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:159:29)
[5/8/2021, 8:10:38 AM] Got SIGTERM, shutting down Homebridge...`

Had to revert to 6.4.0-beta-1 to get ot to stop.

**Comment by Infallibleman** [comment]
sorry wrongly opened here
