### ISSUE TITLE
Error occurs when loading plugin

### ISSUE THREAD

**Issue by bramnet** [NorthernMan54/homebridge-tcc#118]
I noticed a few days ago that our TCC thermostat disappeared from homebridge. I restarted homebridge and took a look at logs, and I'm seeing this below:
```
[9/14/2022, 3:43:47 PM] ====================
[9/14/2022, 3:43:47 PM] ERROR LOADING PLUGIN homebridge-tcc:
[9/14/2022, 3:43:47 PM] Error: /homebridge/node_modules/homebridge-tcc/node_modules/node-expat/build/Release/node_expat.node: wrong ELF class: ELFCLASS32
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/homebridge/node_modules/homebridge-tcc/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
[9/14/2022, 3:43:47 PM] ====================

[9/14/2022, 3:43:48 PM] No plugin was found for the platform "tcc" in your config.json. Please make sure the corresponding plugin is installed correctly.
```
For clarification, I'm running homebridge under the docker image oznu/homebridge:2022-08-09, if there's something I need to do to make this function correctly, please let me know.

**Comment by ogeeVideo** [comment]
Exec into your homebridge container and run: npm install node-expat

**Comment by gchow206** [comment]
I get a similar error, but this is on Mac OS High Sierra (can’t get any later version since it’s on a Mac Mini Mid 2011).  Excerpt from the logs is below…
ERROR LOADING PLUGIN homebridge-tcc:
[11/29/2022, 11:45:15 AM] Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/build/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/build/Debug/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/build/Release/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/out/Debug/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/Debug/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/out/Release/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/Release/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/build/default/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/compiled/16.18.0/darwin/x64/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/addon-build/release/install-root/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/addon-build/debug/install-root/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/addon-build/default/install-root/node_expat.node
 → /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/lib/binding/node-v93-darwin-x64/node_expat.node
    at bindings (/usr/local/lib/node_modules/homebridge-tcc/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-tcc/node_modules/xml2json/lib/xml2json.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)

Any suggestions to fix this?

**Comment by perfectly-preserved-pie** [comment]
> Exec into your homebridge container and run: npm install node-expat

Won't this change just disappear the next time the container restarts?
