### ISSUE TITLE
Installation using native Synology DSM 7 Homebridge not working

### ISSUE THREAD

**Issue by wbuschha** [NorthernMan54/homebridge-tcc#134]
When I have tried to install the TCC plugin in the native Homebridge version for DSM 7, the installation does not finish and reports a long list of errors. Sorry, I didn’t record the error details. Rather, I switched back to the Oznu/Homebridge version within Docker, and that works fine.

**Comment by patrick131** [comment]
My DSM 7 fails with this:
USER: homebridge
DIR: /volume1/homebridge
CMD: npm install --save homebridge-tcc@0.2.34

[##################] - reify:googleapis: timing reifyNode:node_modules/homebridge-tcc/
> node-expat@2.4.0 install
> node-gyp rebuild

gyp ERR! build error - reify:googleapis: timing reifyNode:node_modules/homebridge-tcc/
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 4.4.302+
gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-tcc/node_modules/node-expat
gyp ERR! node -v v17.9.1
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/homebridge-tcc/node_modules/node-expat
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2023-05-28T20_26_26_998Z-debug-0.log

Operation failed. Please review log for details.

**Comment by patrick131** [comment]
Any help would be greatly appreciated.  It was working fine on my 2009 MacPro that I'm retiring.

**Comment by NorthernMan54** [comment]
@patrick131 homebridge-tcc leverages node-gyp to compile code needed for the plugin to operate.  And the Synology environment does not support this without making changes to your setup.   If you google `node-gyp synology dsm` you can see a few guides.

**Comment by wbuschha** [comment]
Hi, thank you for the info. I will check it out.

>

**Comment by patrick131** [comment]
Much appreciated, looking into this now!

**Comment by tc8** [comment]
Please correct me if I'm wrong but the problem seems to be that `make` isn't available, rather than `node-gyp` not being available. 

I have `node-gyp` available but not `make` and I cannot install this plugin.

Is `make` bundled with `node-gyp`? Or does it have to be installed separately?

**Comment by NorthernMan54** [comment]
Make is a compiler tool that is needed with node-gyp, but not included

**Comment by wbuschha** [comment]
I have looked into this, but cannot figure out how to install node-gyp on my Synology NAS. I guess I will have to continue using Homebridge with Docker.Thank you.On May 29, 2023, at 20:56, patrick131 ***@***.***> wrote:﻿
Much appreciated, looking into this now!

**Comment by refactoringdr** [comment]
Even with the upgraded Node.js, I'm getting failures on my DSM 7 system. Looks like something's messed up with libpthread:
```
[7/31/2023, 3:16:23 PM] ====================
[7/31/2023, 3:16:23 PM] ERROR LOADING PLUGIN homebridge-tcc:
[7/31/2023, 3:16:23 PM] Error: /opt/lib/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/volume1/homebridge/node_modules/homebridge-tcc/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/volume1/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/volume1/homebridge/node_modules/homebridge-tcc/node_modules/xml2json/lib/xml2json.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/volume1/homebridge/node_modules/homebridge-tcc/node_modules/xml2json/lib/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
[7/31/2023, 3:16:23 PM] ====================```

**Comment by NorthernMan54** [comment]
As I don't have a DSM, I'm not able to troubleshoot this.

**Comment by Demoleon63** [comment]
Trying to install in Synology DS1821+ with DSM 7.2.1.  and no go.  I installed Entware and re-tried but no luck.  In the log it is looking for something called Make?  Not sure what it is or how to install it on the NAS.  Anyone have any luck installing this?

**Comment by Demoleon63** [comment]
Yes.  Both the Entware and the Apache make script were installed but still no go.  Looks like same error message as before.
