### ISSUE TITLE
Service Log errors 

### ISSUE THREAD

**Issue by Tesla-P100FX** [NorthernMan54/homebridge-tcc#137]
### Current Situation

or Air] pollDevices AxiosError: timeout of 10000ms exceeded

### Logs

```markdown
Logs showed this last night, 

GetLocations Error: AxiosError: timeout of 10000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/var/lib/homebridge/node_modules/homebridge-tcc/node_modules/axios/lib/adapters/http.js:628:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-tcc/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7) {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 10000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: '*/*',
      'Content-Type': 'text/xml;charset=UTF-8',
      'user-agent': 'TCCStageC/1092 CFNetwork/1125.2 Darwin/19.4.0',
      ADRUM: 'isAjax:true',
      'Accept-Language': 'en-ca',
      'Accept-Encoding': 'gzip, deflate, br',
      ADRUM_1: 'isMobile:true',
      soapAction: 'http://services.alarmnet.com/Services/MobileV2/GetLocations',
      'Content-Length': '390'
    },
    method: 'post',
    url: 'https://tccna.honeywell.com/ws/MobileV2.asmx',
    data: '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://services.alarmnet.com/Services/MobileV2/"><soap:Body><GetLocations><sessionID>89FE27C7-2C69-4189-9837-3E8880EF5C5A</sessionID></GetLocations></soap:Body></soap:Envelope>'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/ws/MobileV2.asmx',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      lookup: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'tccna.honeywell.com',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/ws/MobileV2.asmx'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 390,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '390',
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /ws/MobileV2.asmx HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'Content-Type: text/xml;charset=UTF-8\r\n' +
        'user-agent: TCCStageC/1092 CFNetwork/1125.2 Darwin/19.4.0\r\n' +
        'ADRUM: isAjax:true\r\n' +
        'Accept-Language: en-ca\r\n' +
        'Accept-Encoding: gzip, deflate, br\r\n' +
        'ADRUM_1: isMobile:true\r\n' +
        'soapAction: http://services.alarmnet.com/Services/MobileV2/GetLocations\r\n' +
        'Content-Length: 390\r\n' +
        'Host: tccna.honeywell.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/ws/MobileV2.asmx',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'tccna.honeywell.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://tccna.honeywell.com/ws/MobileV2.asmx',
    _timeout: null,
    [Symbol(kCapture)]: false
  }
}
[15/09/2023, 04:11:28] [First Flo
```

### Configuration

```json
{
    "name": "First Floor Air",
    "username": "xxx@outlook.com",
    "password": "xxxxxxxxx",
    "sensors": "inside",
    "refresh": 600,
    "storage": "fs",
    "platform": "tcc",
    "_bridge": {
        "username": "0E:C0:BB:47:F2:83",
        "port": 34843
    }
}
```

### Environment

 
Raspbian GNU/Linux Bullseye (11)
Node.js Version	[v18.16.0 
User	pi
 

### Process Supervisor

launchctl

### Additional Context

.

**Comment by NorthernMan54** [comment]
This appears to be an error triggered by a slow response time from `http://services.alarmnet.com/Services/MobileV2/GetLocations`.

Am thinking that it can be ignored unless it is very repetitive.

**Comment by Tesla-P100FX** [comment]
It does it a cople times daily, is there a way to suppress this log?

**Comment by NorthernMan54** [comment]
Am thinking that is `debug` level logging, can you disable that

**Comment by Tesla-P100FX** [comment]
Debug  level logging  was not enabled.

**Comment by NorthernMan54** [comment]
Looking at the code, and debug is triggering that output.  Do you have `DEBUG=*` in your environment ?

https://github.com/NorthernMan54/homebridge-tcc/blob/0aed8ed56c037775b13f294dacab9ae6dd0c28d2/lib/tcc.js#L361

**Comment by Tesla-P100FX** [comment]
no my jason is the following and that is not set anywhere else int he config  

{
    "name": "First Floor Air",
    "username": "xxxxx@outlook.com",
    "password": "pass",
    "sensors": "inside",
    "refresh": 600,
    "storage": "fs",
    "platform": "tcc",
    "_bridge": {
        "username": "0E:C0:BB:47:F2:83",
        "port": 34843
    }
}
