### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by darrenmadams** [NorthernMan54/homebridge-tcc#142]
### Current Situation

homebridge-tcc seems to have stopped working I think after I was forced to update node-gyp (which I did successfully).  It was initially reporting node.js version errors when I couldn't find my thermostat today:

```
ERROR LOADING PLUGIN homebridge-tcc:
Error: The module '/var/lib/homebridge/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

Tried npm rebuild homebridge-tcc
Tried 'sudo apt-get install build-essential' from another thread and it's current (12.9)
Tried uninstalling homebridge-tcc, rebooting, reinstalling, rebooting.  Now get the following error:

```
ERROR LOADING PLUGIN homebridge-tcc:
Error: Could not locate the bindings file. Tried:
```
(see below for full output)

Hoping to not have to rebuilt my entire Homebridge environment as I have several other devices on it that are configured and working fine.  Also, I have several automations built on those devices I would rather not have to redo if possible.  Thanks!

### Logs

```markdown
[13/12/2023, 13:19:33] ====================
[13/12/2023, 13:19:33] ERROR LOADING PLUGIN homebridge-tcc:
[13/12/2023, 13:19:33] Error: Could not locate the bindings file. Tried:
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/build/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/build/Debug/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/build/Release/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/out/Debug/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/Debug/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/out/Release/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/Release/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/build/default/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/compiled/20.9.0/linux/arm/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/addon-build/release/install-root/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/addon-build/debug/install-root/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/addon-build/default/install-root/node_expat.node
 → /var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/lib/binding/node-v115-linux-arm/node_expat.node
    at bindings (/var/lib/homebridge/node_modules/homebridge-tcc/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-tcc/node_modules/xml2json/lib/xml2json.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-tcc/node_modules/xml2json/lib/index.js:3:18)
[13/12/2023, 13:19:33] ====================
```

### Configuration

```json
{
    "name": "Thermostat",
    "username": "myemail",
    "password": "mypassword",
    "sensors": "none",
    "refresh": 600,
    "storage": "fs",
    "platform": "tcc"
}
```

### Environment

- OS: Raspbian GNU/Linux 11 (bullseye)
- Software: v1.7.0 UI v4.54.1
- Node: v20.9.0
- npm: 10.1.0

### Process Supervisor

not applicable

### Additional Context

Original install using official Homebridge Raspberry Pi Image and updated regularly over the years.

**Comment by NorthernMan54** [comment]
Am thinking the easiest method of resolving would be remove the homebridge-tcc directory from node_modules then reinstall

if you stop homebridge first, do this, then restart it may not even notice

**Comment by darrenmadams** [comment]
Thanks for the response.  By writing out my issue I realized something else to try.

The initial error says to just run "npm rebuild".  That was taking so long I guess I killed it figuring it needed the homebridge-tcc argument.  Turns out just letting npm rebuild on its own for a while and a final forced reboot fixed it.  Sometimes it helps to read error messages :)
