### ISSUE TITLE
No plugin was found on Synology NAS

### ISSUE THREAD

**Issue by tchaffin1** [NorthernMan54/homebridge-tcc#144]
### Current Situation

There is an issue loading the TCC plugin on the Synology NAS. It works perfectly on my Macbook Homebridge, but I get the following errors when loading it on the NAS. 

### Logs

```markdown
====================
[1/28/2024, 10:43:37 PM] ERROR LOADING PLUGIN homebridge-tcc:
[1/28/2024, 10:43:37 PM] Error: /opt/lib/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at bindings (/volume1/homebridge/node_modules/homebridge-tcc/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/volume1/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
```

### Configuration

```json
{
            "name": "Thermostat",
            "username": "****",
            "password": "****",
            "usePermanentHolds": true,
            "sensors": "all",
            "refresh": 600,
            "storage": "fs",
            "debug": true,
            "platform": "tcc",
            "_bridge": {
                "username": "****",
                "port": ****
            }
```

### Environment

- OS: DSM
- Software: Homebridge 3.1.1
- Node: 20.9.0
- npm: 10.1.0

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
This plugin uses native modules and needs this package installed before homebridge-tcc

https://github.com/homebridge/homebridge-syno-spk/wiki/DSM-7:-Enable-Compiling-Of-Native-Modules

**Comment by tchaffin1** [comment]
I did enable that and that fixed the install problem that I was having initially, but I’m still having the issue loading the plugin in the logs above.

**Comment by NorthernMan54** [comment]
Besides suggesting to uninstall the plugin and install again I don’t have anything to suggest

**Comment by carlylemiii** [comment]
I'm seeing this exact same thing (install goes okay), did you ever figure anything out @tatechaffin?

**Comment by tatechaffin** [comment]
> I'm seeing this exact same thing (install goes okay), did you ever figure anything out @tatechaffin?

Never figured anything out, ended up installing it on a Raspberry Pi and it runs fine on that.

**Comment by Demoleon63** [comment]
Having similar issues.  Finally got the plugin to install but now it won't run.  When Homebridge restarts I get the following errors:

[4/7/2024, 4:42:57 PM] ---
[4/7/2024, 4:42:57 PM] ====================
[4/7/2024, 4:42:57 PM] ERROR LOADING PLUGIN homebridge-tcc:
[4/7/2024, 4:42:57 PM] Error: /opt/lib/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at bindings (/volume1/homebridge/node_modules/homebridge-tcc/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/volume1/homebridge/node_modules/homebridge-tcc/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
[4/7/2024, 4:42:57 PM] ====================

**Comment by mnako1** [comment]
Upgraded to a new Synology DS and having the same issue as above while re-installing HomeBridge and the homebridge-tcc plugin.  Curious if anyone has found a solution or work around.

**Comment by NorthernMan54** [comment]
@mnako1 Try the current beta release, I updated the code base and removed the problematic dependency.

**Comment by mnako1** [comment]
> [@mnako1](https://github.com/mnako1) Try the current beta release, I updated the code base and removed the problematic dependency.

Thank you!   I updated to v0.3.1-beta.4 and the plugin started just fine.  Thanks for the great work.
