### ISSUE TITLE
Will homebridge-tcc be updated for Homnbridge V2.0?

### ISSUE THREAD

**Issue by michaelrowe01** [NorthernMan54/homebridge-tcc#147]
### Current Situation

I see in Homebridge that homebridge-tcc shows unknown status for Homebridge v2.0.

### Logs

```markdown
[10/15/2024, 1:12:16 PM] [Thermostat] Existing TCC accessory (deviceID=798829) Upstairs
GetLocations Error: AxiosError: timeout of 10000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/homebridge-tcc/node_modules/axios/lib/adapters/http.js:657:16)
    at RedirectableRequest.emit (node:events:519:28)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-tcc/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
    at Axios.request (/usr/local/lib/node_modules/homebridge-tcc/node_modules/axios/lib/core/Axios.js:45:41)
    at /usr/local/lib/node_modules/homebridge-tcc/lib/tcc.js:322:13 {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 10000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: '*/*',
      'Content-Type': 'text/xml;charset=UTF-8',
      'user-agent': 'TCCStageC/1092 CFNetwork/1125.2 Darwin/19.4.0',
      ADRUM: 'isAjax:true',
      'Accept-Language': 'en-ca',
      'Accept-Encoding': 'gzip, deflate, br',
      ADRUM_1: 'isMobile:true',
      soapAction: 'http://services.alarmnet.com/Services/MobileV2/GetLocations',
      'Content-Length': '390'
    },
    method: 'post',
    url: 'https://tccna.honeywell.com/ws/MobileV2.asmx',
    data: '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://services.alarmnet.com/Services/MobileV2/"><soap:Body><GetLocations><sessionID>7AC29D39-56C7-4C6A-861B-CACC3DF0C361</sessionID></GetLocations></soap:Body></soap:Envelope>'
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Array],
      timeout: undefined,
      abort: undefined
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/ws/MobileV2.asmx',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'tccna.honeywell.com',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/ws/MobileV2.asmx'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 390,
    _requestBodyBuffers: [ [Object] ],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '390',
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /ws/MobileV2.asmx HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'Content-Type: text/xml;charset=UTF-8\r\n' +
        'user-agent: TCCStageC/1092 CFNetwork/1125.2 Darwin/19.4.0\r\n' +
        'ADRUM: isAjax:true\r\n' +
        'Accept-Language: en-ca\r\n' +
        'Accept-Encoding: gzip, deflate, br\r\n' +
        'ADRUM_1: isMobile:true\r\n' +
        'soapAction: http://services.alarmnet.com/Services/MobileV2/GetLocations\r\n' +
        'Content-Length: 390\r\n' +
        'Host: tccna.honeywell.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/ws/MobileV2.asmx',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'tccna.honeywell.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://tccna.honeywell.com/ws/MobileV2.asmx',
    _timeout: null,
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  }
}
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge EC7C",
        "username": "0E:55:B7:49:EC:7C",
        "port": 51343,
        "pin": "934-87-922",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Thermostat",
            "username": "valid@user",
            "password": "validPassword",
            "sensors": "inside",
            "refresh": 600,
            "storage": "fs",
            "_bridge": {
                "username": "0E:83:C4:2E:E4:81",
                "port": 39128
            },
            "platform": "tcc"
        },
        {
            "platform": "EufySecurity",
            "name": "EufySecurity",
            "username": "valid@user",
            "password": "validPassword",
            "country": "US",
            "deviceName": "",
            "_bridge": {
                "username": "0E:A7:10:B1:81:5E",
                "port": 53174
            }
        }
    ],
    "disabledPlugins": [
        "homebridge-eufy-security"
    ]
}
```

### Environment

OS | macOS Sequoia
Homebridge:  v1.8.4
Node.js v20.17.0
nom: 10.8.2

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Tks for the report, I'm in the process of updating all the plugins within my portfolio.  So this is on the list.

**Comment by nbraunstein** [comment]
Really appreciate that. This is definitely my most used plugin and the only one that supports my older thermostat.

Thank you 🙏

**Comment by NorthernMan54** [comment]
The current beta features HB 2.0 support and a fix for #153

**Comment by agilisone** [comment]
Just installed beta 6. Thank you very much for your support and dedication!

**Comment by NorthernMan54** [comment]
Not a problem sir.  Actually I have to applaud the community here as they identified the issue before I had even noticed my personal setup had stopped working.
