### ISSUE TITLE
Error Hostname/IP

### ISSUE THREAD

**Issue by carinconc** [NorthernMan54/homebridge-tcc#153]
### Analysis

Since today, I have been getting the following error in HB log:

Error: Hostname/IP does not match certificate's altnames: Host: tccna.honeywell.com. is not in the cert's altnames: DNS:TCCNA.resideo.com, DNS:TCCEU.resideo.com, DNS:TCCAP.resideo.com, DNS:TCCNAS.resideo.com, DNS:TCCEUS.resideo.com, DNS:TCCAPS.resideo.com

### Expected Behavior

The plugin should connect to TCC and create the accessories

### Steps To Reproduce

The error happens every time HB starts

### Logs

```markdown
[12/12/2024, 7:22:38 AM] [Thermostat] Restarting child bridge...
[12/12/2024, 7:22:38 AM] Got SIGTERM, shutting down child bridge process...
[12/12/2024, 7:22:43 AM] [Thermostat] Child bridge process ended
[12/12/2024, 7:22:43 AM] [Thermostat] Process Ended. Code: 143, Signal: null
[12/12/2024, 7:22:50 AM] [Thermostat] Restarting Process...
[12/12/2024, 7:22:50 AM] [Thermostat] Launched child bridge with PID 8269
[12/12/2024, 7:22:51 AM] Registering platform 'homebridge-tcc.tcc'
[12/12/2024, 7:22:51 AM] [Thermostat] Loaded homebridge-tcc v0.2.34 child bridge successfully
[12/12/2024, 7:22:51 AM] Loaded 0 cached accessories from cachedAccessories.0E5C941F6940.
[12/12/2024, 7:22:51 AM] [Thermostat] didFinishLaunching
Thu, 12 Dec 2024 13:22:51 GMT tcc-lib Setting up TCC component
Thu, 12 Dec 2024 13:22:51 GMT tcc-lib Queue: Working on item #1.  Size: 0  Pending: 0
[12/12/2024, 7:22:51 AM] Homebridge v1.8.5 (HAP v0.12.3) (Thermostat) is running on port 33644.
[12/12/2024, 7:22:51 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[12/12/2024, 7:22:51 AM] [Thermostat] Critical Error - No devices created, please restart.
[12/12/2024, 7:22:51 AM] [Thermostat] Error: Hostname/IP does not match certificate's altnames: Host: tccna.honeywell.com. is not in the cert's altnames: DNS:TCCNA.resideo.com, DNS:TCCEU.resideo.com, DNS:TCCAP.resideo.com, DNS:TCCNAS.resideo.com, DNS:TCCEUS.resideo.com, DNS:TCCAPS.resideo.com
```

### Configuration

```json
{
    "name": "Thermostat",
    "username": "HIDDEN_INFORMATION",
    "password": "HIDDEN_INFORMATION",
    "sensors": "all",
    "refresh": 600,
    "storage": "fs",
    "debug": true,
    "_bridge": {
        "username": "HIDDEN_INFORMATION",
        "port": 33644
    },
    "platform": "tcc"
}
```

### Environment

- OS: Ubuntu Jammy (22.04.5 LTS) (Docker image)
- Software: Homebridge
- Node: v20.18.0
- npm:

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

Image: homebridge/homebridge:latest

**Comment by joshsb9662** [comment]
Can confirm having same issue.

**Comment by willymoyer** [comment]
can confirm I am also unable to control, having the same issue

**Comment by NorthernMan54** [comment]
Well this is good timing, I have added the fix to the current beta, and it looks good.

So if you update to v0.3.0-beta.5 or later, it should be resolved.

As this is also the beta for HB 2.0 support,  if I could get some positive or negative feedback on the beta release. I can publish it as the current release tomorrow.

**Comment by magicallizard** [comment]
Wish I came here before spending half this morning on a fix, anyways this is how I got it working for now.

1. sudo nano /var/lib/homebridge/node_modules/homebridge-tcc/index.js
2. In this file, add the following line near the top, after the other require statements: 

 process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

3. Restart home bridge

**Comment by eweiman** [comment]
Beta 5 resolves the lack of control this morning, thanks for the quick fix.
I've not yet installed HB 2.0, so no feedback there yet from me as i'm pretty sure it will break other things i have.

**Comment by carinconc** [comment]
Beta 5 is giving me a new error:  

[12/12/2024, 1:09:51 PM] [Thermostat] Error: Cannot find module './package.json'
Require stack:
- /homebridge/node_modules/homebridge-tcc/src/index.js
- /homebridge/node_modules/homebridge/lib/plugin.js
- /homebridge/node_modules/homebridge/lib/pluginManager.js
- /homebridge/node_modules/homebridge/lib/api.js
- /homebridge/node_modules/homebridge/lib/childBridgeFork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at new TccSensorsAccessory (/homebridge/node_modules/homebridge-tcc/src/index.js:469:61)
    at /homebridge/node_modules/homebridge-tcc/src/index.js:67:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/homebridge/node_modules/homebridge-tcc/src/index.js',
    '/homebridge/node_modules/homebridge/lib/plugin.js',
    '/homebridge/node_modules/homebridge/lib/pluginManager.js',
    '/homebridge/node_modules/homebridge/lib/api.js',
    '/homebridge/node_modules/homebridge/lib/childBridgeFork.js'
  ]
}

**Comment by carinconc** [comment]
> Wish I came here before spending half this morning on a fix, anyways this is how I got it working for now.
> 
> 1. sudo nano /var/lib/homebridge/node_modules/homebridge-tcc/index.js
> 2. In this file, add the following line near the top, after the other require statements:
> 
> process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
> 
> 3. Restart home bridge

Thanks  @magicallizard, your solution works.

**Comment by johnjensenish** [comment]
The connection issue appears resolved and my devices are responding on on beta 6 w/ Homebridge 1.8.5

**Comment by ijrc01** [comment]
The problem is that an outdated API endpoint is being referenced.

The fix for me was to edit 
`/homebridge/node_modules/homebridge-tcc/lib/tcc.js`

And replace
`const URL = 'https://tccna.**resideo**.com/ws/MobileV2.asmx';`

with 
const URL = 'https://tccna.**honeywell**.com/ws/MobileV2.asmx';
