### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by animosity22** [NorthernMan54/homebridge-tcc#23]
I mistakenly uninstalled and then reinstalled the plugin but using my config that previously worked, I'm getting a login error. I know the user name/password/device id is all good as it worked before.

I'm not sure if something didn't get reinstalled properly but this is the error I'm getting:

```
[1/1/2017, 10:01:52 AM] [Thermostat] Logged into tcc! undefined
[1/1/2017, 10:01:52 AM] [Thermostat] Error during Login: TypeError: Cannot read property 'map' of undefined


    at Object.<anonymous> (/usr/lib/node_modules/homebridge-tcc/index.js:64:40)
    at _fulfilled (/usr/lib/node_modules/homebridge-tcc/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/homebridge-tcc/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/homebridge-tcc/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/homebridge-tcc/node_modules/q/q.js:557:44
    at flush (/usr/lib/node_modules/homebridge-tcc/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by animosity22** [comment]
I see, I updated the module and the config file changed.

I fixed it by updating my config file.
