### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by hollowsquare** [NorthernMan54/homebridge-tcc#55]
[3/3/2020, 22:57:12] [Thermostat] getServices Thermostat
(node:18921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'uiData' of undefined
    at tccAccessory.getServices (/usr/local/lib/node_modules/homebridge-tcc/index.js:402:32)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:427:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:413:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-tcc/index.js:92:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18921) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3/3/2020, 22:57:13] [HB Supervisor] Homebridge Process Ended. Code: 0, Signal: null
[3/3/2020, 22:57:18] [HB Supervisor] Restarting Homebridge...

**Comment by hollowsquare** [comment]
Found a related issue that may solve this for me.

**Comment by NorthernMan54** [comment]
Tks
