### ISSUE TITLE
Problem with update - Plugin no more working

### ISSUE THREAD

**Issue by PatCeretti** [NorthernMan54/homebridge-tcc#60]
Dear, 
the plugin was working correctly with no issue. I did the update to the last verion today and then when I restart Homebridge, I get this message :

[2020-05-09 09 h 07 min 06 s] Loaded plugin: homebridge-tcc
[2020-05-09 09 h 07 min 07 s] ====================
[2020-05-09 09 h 07 min 07 s] ERROR INITIALIZING PLUGIN homebridge-tcc:
[2020-05-09 09 h 07 min 07 s] Error: No valid exports main found for 'C:\Users\patri\AppData\Roaming\npm\node_modules\homebridge-tcc\node_modules\uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\patri\AppData\Roaming\npm\node_modules\homebridge-tcc\node_modules\googleapis-common\build\src\apirequest.js:19:14)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
[2020-05-09 09 h 07 min 07 s] ====================

Then plugin is no more working.

Can you help me to fix it. Thank in advance for your support.

Best regards.

Patrick Ceretti

**Comment by NorthernMan54** [comment]
I’m not sure what the issue is, as this appears to be an issue with npm and installing on windows.

**Comment by PatCeretti** [comment]
Dear

Thank for the feedback.

Yes, I’m using homebridge with windows 10.

**Comment by NorthernMan54** [comment]
@PatCeretti This appears to be a NPM installer on windows issue, and not an actual issue with the plugin.  Unfortunately I won't be able to help with this.

**Comment by PatCeretti** [comment]
Thank for the information. I’ve uninstalled the plugin and I will wait that the issue with NPM will be fixed.

Anyway, I really appreciate your involvement to support my request.

Best regards

Patrick
