### ISSUE TITLE
update/install errors - NPM Version 13.2.0

### ISSUE THREAD

**Issue by jehrler** [NorthernMan54/homebridge-tcc#65]
went to update to latest version and it failed  here's what it told me:

 npm install -g homebridge-tcc
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

**Comment by NorthernMan54** [comment]
Those are warnings and not errors

**Comment by jehrler** [comment]
ok, found out this is an issue with Mac OS Catalina that requires reinstalling Xcode command line tools.

Unfortunately I now have this:

6/8/2020, 11:19:15 AM] Error: The requested platform 'tcc' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
[6/8/2020, 11:19:15 AM] Got SIGTERM, shutting down Homebridge...

**Comment by NorthernMan54** [comment]
Did it install correctly?  When I install on my Mac, it looks like this

```
npm install -g homebridge-tcc
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

> node-expat@2.3.18 install /Users/northernMan/npm/lib/node_modules/homebridge-tcc/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
+ homebridge-tcc@0.2.1
added 56 packages from 98 contributors in 12.002s
```

**Comment by jehrler** [comment]
seemed to:

jehrler@shoreview ~ % npm install -g homebridge-tcc
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

> node-expat@2.3.18 install /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
+ homebridge-tcc@0.2.1
added 56 packages from 98 contributors in 10.171s

**Comment by NorthernMan54** [comment]
I made some minor adjustments to the packaging and the GUI integration.  Can you update and try again.

**Comment by jehrler** [comment]
While the graphic UI noted the update and installed it, this is the result:

[6/8/2020, 9:05:08 PM] ====================
[6/8/2020, 9:05:08 PM] ERROR INITIALIZING PLUGIN homebridge-tcc:
[6/8/2020, 9:05:08 PM] Error: No valid exports main found for '/usr/local/lib/node_modules/homebridge-tcc/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-tcc/node_modules/googleapis-common/build/src/apirequest.js:20:14)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
[6/8/2020, 9:05:08 PM] ====================
[6/8/2020, 9:05:08 PM] Loading 3 platforms...
[6/8/2020, 9:05:08 PM] [Config] Initializing config platform...
[6/8/2020, 9:05:08 PM] [Config] Spawning homebridge-config-ui-x with PID 61398
[6/8/2020, 9:05:08 PM] [GarageDoor] Initializing MyQ2 platform...
[6/8/2020, 9:05:08 PM] Error loading platform requested in your config.json at position 3
[6/8/2020, 9:05:08 PM] Error: The requested platform 'tcc' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
[6/8/2020, 9:05:08 PM] Got SIGTERM, shutting down Homebridge...
[0;37m[6/8/2020, 9:05:09 PM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.21.0 is listening on :: port 8080[0m

**Comment by NorthernMan54** [comment]
Googling the Error shows this "Error: No valid exports main found for "

https://github.com/strongloop/loopback-next/issues/5381

What version of NodeJS are you running?

**Comment by jehrler** [comment]
13.2.0

Regards,

James R Ehrler
ursawagon.com

**Comment by NorthernMan54** [comment]
Downgrade to nodejs version v12.16.X or upgrade to v14.x.x

**Comment by jehrler** [comment]
When installed nodes 12.16.x I got this error:

[6/8/2020, 9:34:20 PM] ERROR LOADING PLUGIN homebridge-tcc:
[6/8/2020, 9:34:20 PM] Error: The module '/usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

uninstalled and then retried with nodejs 14.x.x and it is working!

**Comment by NorthernMan54** [comment]
Glad to hear, everything is okay now?

**Comment by jehrler** [comment]
Yup.  Working great.

Regards,

James R. Ehrler
