### ISSUE TITLE
Still getting "Accessory with the same UUID as another bridged Accessory" after the latest update

### ISSUE THREAD

**Issue by Infallibleman** [NorthernMan54/homebridge-tcc#94]
**Still getting the below error message:**
```
[2/22/2021, 1:36:22 PM] [Thermostat] configureAccessory 1-Upstairs
[2/22/2021, 1:36:22 PM] [Thermostat] configureAccessory 2-Downstairs
[2/22/2021, 1:36:22 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d59511c0-67f9-42da-87e0-2e8265e894b0
    at Bridge.Accessory._this.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:419:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:308:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/lib/node_modules/homebridge/src/server.ts:268:69)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:156:10)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
[2/22/2021, 1:36:22 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by NorthernMan54** [comment]
Do you have another device in this homebridge instance with the same name?

**Comment by Infallibleman** [comment]
I don't.  I uninstalled the plugin and the server came up without issues.

**Comment by NorthernMan54** [comment]
Awesome
